/* FILENAME: DEF.H
 * PROGRAMMER: DS6
 * PURPOSE: Default definitions.
 * LAST UPDATE: 08.06.2015
 */

#ifndef __DEF_H_
#define __DEF_H_


#pragma warning(disable: 4244 4305 4133)

#include <windows.h>

/* Large integer types */
typedef __int64 INT64;
typedef unsigned __int64 UINT64;

/* Common purpose float-point data type */
typedef float FLT;
typedef double DBL;
typedef long double LDBL;


#endif /* __DEF_H_ */

/* END OF 'DEF.H' FILE */
